#!/bin/bash

#export UICADMIN_HOME="/var/akio/uic-admin"
#export UICADMIN_DATA="/var/akio/uic-admin-data"
#export UICADMIN_CONF="$UICADMIN_HOME/akio-cim-admin-conf/conf"
#setenv uic-admin.contextFile="$UICADMIN_HOME/akio-cim-admin-conf/context-tomcat.xml"
#setenv com.atomikos.icatch.file="$UICADMIN_HOME/akio-cim-admin-conf/transactions.properties"

export MAVEN_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=8886,suspend=n,server=y \
-Xms256m -Xmx512m -XX:MaxPermSize=128m"

#mvn -Dmaven.surefire.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8888 -Xnoagent -Djava.compiler=NONE" clean package

mvn -Dmaven.surefire.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8888 -Xnoagent -Djava.compiler=NONE" clean package
